cmake: Detect armv7l as ARM architecture (#273)
* cmake: Detect armv7l as ARM architecture

On Ubuntu armhf:

```
$ uname -p
armv7l
```

So detect `armv7l` as ARM architecture as well.

* cmake: detect armv8l as ARM architecture

* 32bit: Add missing declaration of *PLONG_PTR fixing a FTBFS such as:

profiler/src/ProcDumpProfiler.cpp:1255:30: error: use of undeclared identifier 'PLONG_PTR'
 1255 | msgField = *(PLONG_PTR)(((BYTE *)objectId) + pFieldOffsets[fieldIndex].ulOffset);
      | ^
profiler/src/ProcDumpProfiler.cpp:1256:29: warning: comparison between NULL and non-pointer ('LONG_PTR' (aka 'int') and NULL) [-Wnull-arithmetic]

---------

Co-authored-by: Benjamin Drung <benjamin.drung@canonical.com>
Co-authored-by: Gianfranco Costamagna <locutusofborg@debian.org>